/*
 * generated by Xtext
 */
package de.cau.cs.kieler.scl.ide;

import org.eclipse.xtext.ide.editor.contentassist.IPrefixMatcher;
import org.eclipse.xtext.ide.editor.contentassist.FQNPrefixMatcher;
import de.cau.cs.kieler.core.ls.NoContentAssistService;
import org.eclipse.xtext.ide.server.contentassist.ContentAssistService;
import org.eclipse.xtext.ide.DefaultIdeModule;
import org.eclipse.xtext.ide.refactoring.IRenameStrategy2;
import org.eclipse.xtext.ide.server.rename.IRenameService2;
import org.eclipse.xtext.ide.server.rename.RenameService2;

/**
 * Manual modifications go to {@link SCLIdeModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSCLIdeModule extends DefaultIdeModule {

	// contributed by org.eclipse.xtext.xtext.generator.exporting.QualifiedNamesFragment2
	public Class<? extends IPrefixMatcher> bindIPrefixMatcher() {
		return FQNPrefixMatcher.class;
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.ui.refactoring.RefactorElementNameFragment2
	public Class<? extends IRenameService2> bindIRenameService2() {
		return RenameService2.class;
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.ui.refactoring.RefactorElementNameFragment2
	public Class<? extends IRenameStrategy2> bindIRenameStrategy2() {
		return IRenameStrategy2.DefaultImpl.class;
	}
	
	// sccharts-lite: this grammar's content-assist parser is not part of the build.
	public Class<? extends ContentAssistService> bindContentAssistService() {
		return NoContentAssistService.class;
	}
	
}
