/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kexpressions.ide.keffects;

import org.eclipse.xtext.ide.editor.contentassist.IPrefixMatcher;
import org.eclipse.xtext.ide.editor.contentassist.FQNPrefixMatcher;
import de.cau.cs.kieler.core.ls.NoContentAssistService;
import com.google.inject.Binder;
import com.google.inject.name.Names;
import de.cau.cs.kieler.core.ls.NoContentAssistLexer;
import de.cau.cs.kieler.core.ls.NoContentAssistParser;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.ide.server.contentassist.ContentAssistService;
import org.eclipse.xtext.ide.DefaultIdeModule;
import org.eclipse.xtext.ide.refactoring.IRenameStrategy2;
import org.eclipse.xtext.ide.server.rename.IRenameService2;
import org.eclipse.xtext.ide.server.rename.RenameService2;

/**
 * Manual modifications go to {@link KEffectsIdeModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractKEffectsIdeModule extends DefaultIdeModule {

	// contributed by org.eclipse.xtext.xtext.generator.exporting.QualifiedNamesFragment2
	public Class<? extends IPrefixMatcher> bindIPrefixMatcher() {
		return FQNPrefixMatcher.class;
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.ui.refactoring.RefactorElementNameFragment2
	public Class<? extends IRenameService2> bindIRenameService2() {
		return RenameService2.class;
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.ui.refactoring.RefactorElementNameFragment2
	public Class<? extends IRenameStrategy2> bindIRenameStrategy2() {
		return IRenameStrategy2.DefaultImpl.class;
	}
	
	// sccharts-lite: this grammar's content-assist parser is not part of the build.
	public Class<? extends ContentAssistService> bindContentAssistService() {
		return NoContentAssistService.class;
	}
	
	// sccharts-lite: the content-assist service still injects a lexer and parser, so bind stand-ins.
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class)
			.annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST))
			.to(NoContentAssistLexer.class);
	}
	
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return NoContentAssistParser.class;
	}
	
}
